language: rust
rust:
  - stable
  - beta
  - nightly
notifications:
  email:
    - msierks117@gmail.com
before_script:
  - rustc --version
  - cargo --version
script:
  - cargo build
  - cargo test
branches:
  only:
    - master
